name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug and what you expected to happen
      placeholder: |
        When I... I expected... but instead...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce
      description: Steps to reproduce the issue
      placeholder: |
        1. Run `copier copy ...`
        2. ...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: |
        OS: Ubuntu 22.04
        Python: 3.11.5
        Copier: 9.3.1
      value: |
        OS:
        Python:
        Copier:
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Logs, screenshots, or anything else that might help
      render: shell
